#! /usr/bin/sh
#
# Workaround for daily jobs on a laptop, runs several times during the day.

if [ -n "${0%cron-daily}" ]
then
  cd ${0%cron-daily}
fi

# Is datestamp new?
date -I | diff -N -w - .cron.daily > /dev/null
if [ $? -ne 0 ]
then
   SINATRA_ACTIVESUPPORT_WARNING=false ~/.rvm/wrappers/ruby-2.4.0/bundle exec padrino rake db:backup -e production MAX=6
   SINATRA_ACTIVESUPPORT_WARNING=false ~/.rvm/wrappers/ruby-2.4.0/bundle exec padrino runner -e production 'Aging.perform'

  date -I > .cron.daily
fi
