PAGE_SIZE = 8

# How many days to keep zombies (Posts that have been dropped from their Feed)
DAYS_OF_THE_DEAD = 30

# PAGINATION bitmasks
FEED_TOP = 0b1000
FEED_BOTTOM = 0b0100
POST_TOP = 0b0010
POST_BOTTOM = 0b0001

TOP_PAGINATION = FEED_TOP | POST_TOP	# PAGINATION default value 
BOTTOM_PAGINATION = FEED_BOTTOM | POST_BOTTOM

PAGINATION = ENV['AMETHYST_PAGINATION'] ? ENV['AMETHYST_PAGINATION'].to_i(2) : TOP_PAGINATION
PAGINATED = PAGINATION != 0
